version = "1.3.*"
upstream_repository = "https://github.com/lepture/authlib"
requires = ["cryptography", "django-stubs", "flask", "Flask-SQLAlchemy", "httpx", "pycryptodomex>=3.10,<4", "types-requests", "starlette", "werkzeug"]
